keys:
  - &toledo   age10prc9j3uu03exr554w8pyh6dmt0v5vpuxkd3z209tymryx76tgqqhn554v
  - &servidor age1qq0jtpt03xhxv5440q9vjr5v6hp76gcjgx4qyvdnw8sy4q6r0q6qfxp735
  - &laptop   age10prc9j3uu03exr554w8pyh6dmt0v5vpuxkd3z209tymryx76tgqqhn554v # TODO: reemplazar con clave real del laptop

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *toledo
          - *servidor
          - *laptop

  - path_regex: secrets/toledo\.yaml$
    key_groups:
      - age:
          - *toledo

  - path_regex: secrets/servidor\.yaml$
    key_groups:
      - age:
          - *toledo
          - *servidor

  - path_regex: secrets/laptop\.yaml$
    key_groups:
      - age:
          - *toledo
          - *laptop
